name: Build libmpv-android

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

env: 
  NDK_VER: 25.1.8937393
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: General Developer Action
        uses: General-Developer/general-developer-action@0.0.8
        with:
          flutter_channel: stable
          flutter_version: 3.29.0
          is_use_cache: true
          flutter_cache_key: "flutter-path-${{ runner.os }}-3.29.0"
          install_dependencies_developer: "false" # installing git ffmpeg mpv cmake cpp aand more
          install_java: "false" # Instalaling java

      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          distribution: temurin
          java-version: 11
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.3.3
        
      - name: Symlink SDK
        working-directory: ./buildscripts
        run: |
          mkdir sdk
          ln -s ${ANDROID_HOME} ./sdk/android-sdk-linux
          
      - name: Bundle (default)
        working-directory: ./buildscripts
        run: |
          sudo chmod +x bundle_default.sh
          ./bundle_default.sh
      # - name: Bundle (full)
      #   working-directory: ./buildscripts
      #   run: |
      #     sudo chmod +x bundle_full.sh
      #     ./bundle_full.sh
      # - name: Bundle (encoders-gpl)
      #   working-directory: ./buildscripts
      #   run: |
      #     sudo chmod +x bundle_encoders-gpl.sh
      #     ./bundle_encoders-gpl.sh
          
      - uses: actions/upload-artifact@v4.6.1
        with:
          name: artifact
          path: ./output/*
      # - uses: softprops/action-gh-release@v1
      - uses: softprops/action-gh-release@v2.2.1 
        with:
          draft: true
          prerelease: false
          tag_name: "vnext"
          files: |
            output/*
 
 